apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-agent
spec:
  containers:
  - name: jenkins-agent-node
    image: nexus.bmpdtravel.com:5001/jenkins-agent:node
    command:
    - /bin/cat
    tty: true    
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
